// Command gopy-build transpiles every .py file in a directory into a sibling
// .go file, all sharing the same Go package. Cross-module references work
// because Python identifiers in different files map onto the same Go package
// namespace; `from foo import bar` is dropped at lowering time.
//
// Usage:
//
//	gopy-build [-pkg main] [-o outdir] srcdir
//
// If -o is omitted, .go files are written next to their .py sources.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/rroblf01/gopy/ir"
	"github.com/rroblf01/gopy/parser"
	"github.com/rroblf01/gopy/transpile"
)

func main() {
	pkg := flag.String("pkg", "main", "Go package name")
	outDir := flag.String("o", "", "output directory (default: alongside sources)")
	dumper := flag.String("dumper", "", "path to scripts/py_ast_dump.py (default: auto-locate)")
	python := flag.String("python", "", "Python interpreter to use (default: ./.venv/bin/python3 if present, else python3)")
	flag.Parse()
	if flag.NArg() != 1 {
		fmt.Fprintln(os.Stderr, "usage: gopy-build [-pkg name] [-o outdir] srcdir")
		os.Exit(2)
	}
	srcDir := flag.Arg(0)
	info, err := os.Stat(srcDir)
	if err != nil {
		die(err.Error())
	}
	if !info.IsDir() {
		die("srcdir must be a directory")
	}

	dumperPath := *dumper
	if dumperPath == "" {
		dumperPath = locateDumper()
		if dumperPath == "" {
			die("cannot locate py_ast_dump.py (pass -dumper)")
		}
	}

	dest := *outDir
	if dest == "" {
		dest = srcDir
	} else {
		check(os.MkdirAll(dest, 0o755))
	}

	entries, err := os.ReadDir(srcDir)
	check(err)
	sharedHelpers := map[string]string{}
	sharedImports := map[string]bool{}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".py") {
			continue
		}
		pyPath := filepath.Join(srcDir, e.Name())
		pyBin := *python
		if pyBin == "" {
			pyBin = parser.LocatePython(srcDir)
		}
		root, err := parser.ParseFileWith(pyBin, dumperPath, pyPath)
		if err != nil {
			die(fmt.Sprintf("%s: %v", pyPath, err))
		}
		mod, err := ir.Lower(e.Name(), root)
		if err != nil {
			die(fmt.Sprintf("%s: %v", pyPath, err))
		}
		// SkipHelpers=true so each per-file translation never emits
		// duplicate runtime helpers. We gather them across all files
		// and write a single shared gopy_runtime.go at the end.
		src, meta, err := transpile.ModuleWithMeta(mod, transpile.Options{
			PackageName:  *pkg,
			SkipHelpers:  true,
			SourceModule: e.Name(),
		})
		if err != nil {
			die(fmt.Sprintf("%s: %v", pyPath, err))
		}
		for k, v := range meta.Helpers {
			sharedHelpers[k] = v
		}
		for _, imp := range meta.Imports {
			sharedImports[imp] = true
		}
		outFile := filepath.Join(dest, strings.TrimSuffix(e.Name(), ".py")+".go")
		check(os.WriteFile(outFile, src, 0o644))
		fmt.Fprintf(os.Stderr, "wrote %s\n", outFile)
	}
	if len(sharedHelpers) > 0 {
		runtimePath := filepath.Join(dest, "gopy_runtime.go")
		runtimeSrc := renderRuntime(*pkg, sharedHelpers, sharedImports)
		check(os.WriteFile(runtimePath, runtimeSrc, 0o644))
		fmt.Fprintf(os.Stderr, "wrote %s\n", runtimePath)
	}
}

// renderRuntime builds the shared gopy_runtime.go file containing every
// inline helper used across the project, plus the imports those helpers
// rely on. Helper keys are sorted so output is deterministic. The Go
// source is sent through go/format so per-file diffs stay clean.
func renderRuntime(pkg string, helpers map[string]string, importSet map[string]bool) []byte {
	keys := make([]string, 0, len(helpers))
	for k := range helpers {
		keys = append(keys, k)
	}
	sortStrings(keys)
	imps := make([]string, 0, len(importSet))
	for k := range importSet {
		imps = append(imps, k)
	}
	sortStrings(imps)

	var b strings.Builder
	b.WriteString("// Code generated by gopy-build. DO NOT EDIT.\n\n")
	b.WriteString("package ")
	b.WriteString(pkg)
	b.WriteString("\n\n")
	if len(imps) > 0 {
		b.WriteString("import (\n")
		for _, i := range imps {
			b.WriteString("\t\"")
			b.WriteString(i)
			b.WriteString("\"\n")
		}
		b.WriteString(")\n\n")
	}
	for _, k := range keys {
		b.WriteString(helpers[k])
		b.WriteString("\n\n")
	}
	out := []byte(b.String())
	formatted, err := format.Source(out)
	if err != nil {
		// gofmt failure prints the raw source so the user can fix it
		// manually; the build will then surface a precise location.
		fmt.Fprintf(os.Stderr, "gopy-build: gopy_runtime.go gofmt: %v\n", err)
		return out
	}
	return formatted
}

// sortStrings is a thin wrapper to keep the import block of this file
// from growing — using sort.Strings would also work but pulls in sort
// just for one call.
func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j-1] > s[j]; j-- {
			s[j-1], s[j] = s[j], s[j-1]
		}
	}
}

func locateDumper() string {
	candidates := []string{}
	if _, file, _, ok := runtime.Caller(0); ok {
		candidates = append(candidates, filepath.Join(filepath.Dir(file), "..", "..", "scripts", "py_ast_dump.py"))
	}
	if cwd, err := os.Getwd(); err == nil {
		candidates = append(candidates,
			filepath.Join(cwd, "scripts", "py_ast_dump.py"),
			filepath.Join(cwd, "..", "scripts", "py_ast_dump.py"),
		)
	}
	for _, p := range candidates {
		if _, err := os.Stat(p); err == nil {
			abs, _ := filepath.Abs(p)
			return abs
		}
	}
	return ""
}

func check(err error) {
	if err != nil {
		die(err.Error())
	}
}

func die(msg string) {
	fmt.Fprintln(os.Stderr, "gopy-build:", msg)
	os.Exit(1)
}
