#!/usr/bin/env bash
# Run every bench_*.py fixture through gopy-bench, summarize results, and
# splice the summary into README.md between BENCH_START / BENCH_END markers.
# Run from the repo root.
set -euo pipefail

cd "$(dirname "$0")/.."

readme="README.md"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "<!-- BENCH_START -->"
  echo
  echo "_Generated by \`scripts/update_bench.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
  echo
  echo "| Benchmark | CPython (ms) | gopy Go (ms) | Speedup | Python RSS (MB) | gopy RSS (MB) | RSS save |"
  echo "|-----------|-------------:|-------------:|--------:|----------------:|--------------:|---------:|"

  for fixture in tests/fixtures/bench_*.py; do
    name="$(basename "$fixture" .py)"
    out="$(go run ./cmd/gopy-bench -n 5 -warmup 1 "$fixture" 2>&1)"
    py_ms=$(awk '/=== CPython ===/{f=1; next} f && /wall ms/ {match($0, /mean=([0-9.]+)/, a); print a[1]; exit}' <<<"$out")
    go_ms=$(awk '/=== gopy Go ===/{f=1; next} f && /wall ms/ {match($0, /mean=([0-9.]+)/, a); print a[1]; exit}' <<<"$out")
    py_mb=$(awk '/=== CPython ===/{f=1; next} f && /RSS  MB/ {match($0, /mean=([0-9.]+)/, a); print a[1]; exit}' <<<"$out")
    go_mb=$(awk '/=== gopy Go ===/{f=1; next} f && /RSS  MB/ {match($0, /mean=([0-9.]+)/, a); print a[1]; exit}' <<<"$out")
    speedup=$(awk -v p="$py_ms" -v g="$go_ms" 'BEGIN{ if (g>0) printf "%.1fx", p/g; else print "n/a" }')
    rss_save=$(awk -v p="$py_mb" -v g="$go_mb" 'BEGIN{ if (g>0) printf "%.2fx", p/g; else print "n/a" }')
    printf "| %s | %s | %s | %s | %s | %s | %s |\n" "$name" "$py_ms" "$go_ms" "$speedup" "$py_mb" "$go_mb" "$rss_save"
  done
  echo
  echo "_Hardware: $(uname -srm). Go: $(go version | awk '{print $3}'). Python: $(python3 --version | awk '{print $2}')._"
  echo
  echo "<!-- BENCH_END -->"
} >"$tmp"

# Splice into README.md between the sentinels.
python3 - "$readme" "$tmp" <<'PY'
import sys, pathlib, re
readme_path = pathlib.Path(sys.argv[1])
block = pathlib.Path(sys.argv[2]).read_text()
text = readme_path.read_text()
pattern = re.compile(r"<!-- BENCH_START -->.*?<!-- BENCH_END -->", re.DOTALL)
if not pattern.search(text):
    raise SystemExit("README.md is missing BENCH_START/BENCH_END sentinels")
new = pattern.sub(block.strip(), text)
readme_path.write_text(new)
print(f"updated {readme_path}")
PY
